// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8TjLoRt1PkX3qII-D_WQ3LlOLyvJjD38',
    appId: '1:974030449466:web:014219569cef8db821be03',
    messagingSenderId: '974030449466',
    projectId: 'tajweed-corrector',
    authDomain: 'tajweed-corrector.firebaseapp.com',
    storageBucket: 'tajweed-corrector.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXl0X8r3EbcDQzI6kpTRIjrGfPkaZBcwY',
    appId: '1:974030449466:android:6a4fa2db0bd887f221be03',
    messagingSenderId: '974030449466',
    projectId: 'tajweed-corrector',
    storageBucket: 'tajweed-corrector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1ACjV7UUN_8FP0fe3Vz47Cnua1DlBFU',
    appId: '1:974030449466:ios:358006e99529abbc21be03',
    messagingSenderId: '974030449466',
    projectId: 'tajweed-corrector',
    storageBucket: 'tajweed-corrector.firebasestorage.app',
    iosBundleId: 'com.example.tajweedCorrector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1ACjV7UUN_8FP0fe3Vz47Cnua1DlBFU',
    appId: '1:974030449466:ios:358006e99529abbc21be03',
    messagingSenderId: '974030449466',
    projectId: 'tajweed-corrector',
    storageBucket: 'tajweed-corrector.firebasestorage.app',
    iosBundleId: 'com.example.tajweedCorrector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8TjLoRt1PkX3qII-D_WQ3LlOLyvJjD38',
    appId: '1:974030449466:web:84e38ff17cf2912a21be03',
    messagingSenderId: '974030449466',
    projectId: 'tajweed-corrector',
    authDomain: 'tajweed-corrector.firebaseapp.com',
    storageBucket: 'tajweed-corrector.firebasestorage.app',
  );
}
