import 'package:flutter/material.dart';

class TajweedLesson {
  final String id;
  final String title;
  final String arabicTitle;
  final String description;
  final String icon;
  final Color color;
  final String duration;
  final List<LessonSection> sections;
  final List<QuizQuestion> questions;

  TajweedLesson({
    required this.id,
    required this.title,
    required this.arabicTitle,
    required this.description,
    required this.icon,
    required this.color,
    required this.duration,
    required this.sections,
    required this.questions,
  });
}

class LessonSection {
  final String title;
  final String explanation;
  final String arabicExample;
  final String transliteration;
  final String tip;
  final int exampleSurah;
  final int exampleAyah;
  final bool showWordByWord;

  LessonSection({
    required this.title,
    required this.explanation,
    required this.arabicExample,
    required this.transliteration,
    required this.tip,
    required this.exampleSurah,
    required this.exampleAyah,
    required this.showWordByWord,
  });
}

class QuizQuestion {
  final String question;
  final String? arabicText;
  final List<String> options;
  final int correctIndex;
  final String explanation;

  QuizQuestion({
    required this.question,
    this.arabicText,
    required this.options,
    required this.correctIndex,
    required this.explanation,
  });
}

// Hardcoded lessons data
final List<TajweedLesson> lessons = [
  TajweedLesson(
    id: "lesson_1",
    title: "Arabic Letters & Sounds",
    arabicTitle: "الحروف العربية",
    description: "Learn the 28 Arabic letters and their basic sounds",
    icon: "أ",
    color: const Color(0xFF1565C0),
    duration: "10 min",
    sections: [
      LessonSection(
        title: "The Arabic Alphabet",
        explanation: "Arabic has 28 letters. It is read from RIGHT to LEFT. Every letter is a consonant. Vowels are shown as small marks called Harakat.",
        arabicExample: "أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي",
        transliteration: "a b t th j H kh d dh r z s sh S D T DH ' gh f q k l m n h w y",
        tip: "Arabic is always read RIGHT to LEFT — opposite of English!",
        exampleSurah: 1,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Sun Letters — الحروف الشمسية",
        explanation: "When the word 'al' (ال) comes before a Sun Letter, the 'l' sound disappears and the Sun Letter gets a shadda (doubled).\n\nSun letters: ت ث د ذ ر ز س ش ص ض ط ظ ل ن",
        arabicExample: "الشَّمْسُ = ash-shamsu (NOT al-shamsu)\nالنُّورُ = an-nooru\nالرَّحْمَـٰنِ = ar-rahmani",
        transliteration: "ash-shamsu, an-nooru, ar-rahmani",
        tip: "14 Sun letters — the 'l' of 'al' merges into them!",
        exampleSurah: 1,
        exampleAyah: 3,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Moon Letters — الحروف القمرية",
        explanation: "When 'al' (ال) comes before a Moon Letter, pronounce the 'l' clearly.\n\nMoon letters: ء ب ج ح خ ع غ ف ق ك م و ه ي",
        arabicExample: "الْقَمَرُ = al-qamaru\nالْحَمْدُ = al-hamdu\nالْكِتَابُ = al-kitaabu",
        transliteration: "al-qamaru, al-hamdu, al-kitaabu",
        tip: "14 Moon letters — 'al' is always pronounced clearly before them",
        exampleSurah: 1,
        exampleAyah: 2,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "Arabic is read in which direction?",
        arabicText: null,
        options: ["Left to right", "Right to left", "Top to bottom", "Any direction"],
        correctIndex: 1,
        explanation: "Arabic is always read from right to left",
      ),
      QuizQuestion(
        question: "الشَّمْسُ — which type of letter is ش?",
        arabicText: "الشَّمْسُ",
        options: ["Moon letter", "Sun letter", "Neither", "Both"],
        correctIndex: 1,
        explanation: "ش is a sun letter — the lam of al is absorbed",
      ),
      QuizQuestion(
        question: "الْقَمَرُ — how is 'al' pronounced?",
        arabicText: "الْقَمَرُ",
        options: ["Absorbed", "Clearly", "Silent", "Doubled"],
        correctIndex: 1,
        explanation: "ق is a moon letter — al is pronounced clearly",
      ),
      QuizQuestion(
        question: "How many letters in Arabic alphabet?",
        arabicText: null,
        options: ["24", "26", "28", "30"],
        correctIndex: 2,
        explanation: "Arabic has exactly 28 letters",
      ),
      QuizQuestion(
        question: "الرَّحْمَـٰنِ — the ر here is?",
        arabicText: "الرَّحْمَـٰنِ",
        options: ["Moon letter", "Sun letter", "Neither", "Both"],
        correctIndex: 1,
        explanation: "ر is a sun letter — ar-rahmani, not al-rahmani",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_2",
    title: "Harakat — Vowel Marks",
    arabicTitle: "الحركات",
    description: "Master fatha, damma, kasra, sukoon, tanwin and shadda",
    icon: "◌َ",
    color: const Color(0xFF2E7D32),
    duration: "12 min",
    sections: [
      LessonSection(
        title: "Fatha, Damma, Kasra",
        explanation: "Three short vowels:\n\n• Fatha (َ) — above letter — short 'a' sound\n  Example: بَ = 'ba'\n\n• Damma (ُ) — above letter — short 'u' sound\n  Example: بُ = 'bu'\n\n• Kasra (ِ) — below letter — short 'i' sound\n  Example: بِ = 'bi'",
        arabicExample: "بَسْمَلَة\nبِسْمِ ٱللَّهِ",
        transliteration: "basmalah | bismillah",
        tip: "Above = a or u | Below = i",
        exampleSurah: 1,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Sukoon & Shadda",
        explanation: "• Sukoon (ْ) — small circle above — NO vowel, stop the sound\n  Example: بْ = just 'b' then stop\n\n• Shadda (ّ) — small 'w' shape — DOUBLE the letter\n  Example: إِنَّ = in-na (noon doubled)",
        arabicExample: "مِنْ = min (noon with sukoon)\nإِنَّ = inna (noon doubled with shadda)",
        transliteration: "min, inna",
        tip: "Sukoon = stop | Shadda = double the letter",
        exampleSurah: 1,
        exampleAyah: 7,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Tanwin — Double Vowels",
        explanation: "Tanwin adds 'n' sound at end of words:\n\n• Tanwin Fath (ً) = 'an' sound\n• Tanwin Damm (ٌ) = 'un' sound\n• Tanwin Kasr (ٍ) = 'in' sound\n\nTanwin only appears at END of words.",
        arabicExample: "كِتَابًا = kitaaban\nرَجُلٌ = rajulun\nبَيْتٍ = baytin",
        transliteration: "kitaaban, rajulun, baytin",
        tip: "Tanwin only at END of words — adds nasal 'n' sound",
        exampleSurah: 112,
        exampleAyah: 1,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "What sound does فَ make?",
        arabicText: "فَ",
        options: ["fi", "fu", "fa", "f only"],
        correctIndex: 2,
        explanation: "Fatha (َ) above letter = short 'a': fa",
      ),
      QuizQuestion(
        question: "What does sukoon (ْ) mean?",
        arabicText: "مِنْ",
        options: ["Long vowel", "Double letter", "No vowel - stop", "Short 'u'"],
        correctIndex: 2,
        explanation: "Sukoon means stop — no vowel sound after this letter",
      ),
      QuizQuestion(
        question: "إِنَّ — what does shadda do here?",
        arabicText: "إِنَّ",
        options: ["Makes long vowel", "Doubles the noon", "Stops the sound", "Adds 'n' at end"],
        correctIndex: 1,
        explanation: "Shadda doubles the letter: noon is said twice (in-na)",
      ),
      QuizQuestion(
        question: "Tanwin appears where?",
        arabicText: "كِتَابًا",
        options: ["Start of word", "Middle only", "End of word", "Anywhere"],
        correctIndex: 2,
        explanation: "Tanwin only appears at the end of words",
      ),
      QuizQuestion(
        question: "فُ sounds like?",
        arabicText: "فُ",
        options: ["fa", "fi", "fu", "f"],
        correctIndex: 2,
        explanation: "Damma (ُ) above letter = short 'u': fu",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_3",
    title: "Makharij — Letter Origins",
    arabicTitle: "مخارج الحروف",
    description: "Learn where each letter is produced in your mouth and throat",
    icon: "م",
    color: const Color(0xFFE65100),
    duration: "15 min",
    sections: [
      LessonSection(
        title: "What is Makharij?",
        explanation: "Makharij (مخارج) means 'exit points'. Every Arabic letter originates from a specific place:\n\n• Throat (الحلق)\n• Tongue (اللسان)\n• Lips (الشفتان)\n• Nose (الخيشوم)\n\nSaying letters from wrong place = wrong pronunciation!",
        arabicExample: "ق — back of tongue\nب — lips\nن — nose tip of tongue",
        transliteration: "qaf, ba, noon",
        tip: "Say each letter slowly — feel WHERE it vibrates in your mouth",
        exampleSurah: 1,
        exampleAyah: 1,
        showWordByWord: false,
      ),
      LessonSection(
        title: "Throat Letters — حروف الحلق",
        explanation: "6 letters come from the throat at 3 levels:\n\n• Deepest: ء ه (glottal — from very bottom of throat)\n• Middle: ع ح (middle of throat)\n• Upper: غ خ (upper throat/near mouth)\n\nThese 6 are: ء ه ع ح غ خ",
        arabicExample: "أَعُوذُ — هُوَ — عَلِيم — حَكِيم — غَفُور — خَبِير",
        transliteration: "a'oodhu, huwa, 'aleem, hakeem, ghafoor, khabeer",
        tip: "Put hand on throat — feel throat vibrate for these letters",
        exampleSurah: 112,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Lip Letters — حروف الشفتان",
        explanation: "4 letters from the lips:\n\n• ب — both lips fully together (with puff)\n• م — both lips together (nasal)\n• و — lips rounded, not touching\n• ف — upper teeth on lower lip",
        arabicExample: "بِسْمِ — مَالِك — وَلَا — فِي",
        transliteration: "bismi, maalik, walaa, fee",
        tip: "Watch your lips in a mirror while saying these letters",
        exampleSurah: 1,
        exampleAyah: 4,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Heavy vs Light Letters",
        explanation: "Heavy letters (Tafkhim — تفخيم):\nص ض ط ظ ق غ خ\nBack of tongue rises — mouth feels FULL\n\nLight letters (Tarqiq — ترقيق):\nAll other letters\nTongue stays flat — mouth feels THIN\n\nSpecial: ر and ل in Allah's name change based on vowel before them",
        arabicExample: "صِرَاط (heavy ص) vs سِرَاج (light س)\nطَرِيق (heavy ط) vs تَرِيك (light ت)",
        transliteration: "siraata vs siraaj, tareeq vs tarak",
        tip: "Heavy letters: feel your tongue pull back. Light: tongue stays forward",
        exampleSurah: 1,
        exampleAyah: 6,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "Where is ب produced?",
        arabicText: "بِ",
        options: ["Throat", "Tongue tip", "Lips", "Nose"],
        correctIndex: 2,
        explanation: "Ba is a lip letter — both lips come fully together",
      ),
      QuizQuestion(
        question: "How many throat letters are there?",
        arabicText: "ء ه ع ح غ خ",
        options: ["4", "5", "6", "8"],
        correctIndex: 2,
        explanation: "6 throat letters: ء ه ع ح غ خ at 3 throat levels",
      ),
      QuizQuestion(
        question: "ص is which type of letter?",
        arabicText: "صِرَاط",
        options: ["Light (Tarqiq)", "Heavy (Tafkhim)", "Lip letter", "Throat letter"],
        correctIndex: 1,
        explanation: "ص is always heavy — back of tongue rises",
      ),
      QuizQuestion(
        question: "How to test if a letter has Ghunnah?",
        arabicText: "إِنَّ",
        options: ["Open mouth wide", "Pinch your nose", "Touch teeth with tongue", "Close your eyes"],
        correctIndex: 1,
        explanation: "Pinch nose — if sound changes, you have proper Ghunnah",
      ),
      QuizQuestion(
        question: "ف is produced how?",
        arabicText: "فِي",
        options: ["Both lips together", "Upper teeth on lower lip", "Tongue on teeth", "Back of throat"],
        correctIndex: 1,
        explanation: "Fa: upper teeth rest on lower lip while air passes",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_4",
    title: "Noon Sakinah & Tanwin",
    arabicTitle: "النون الساكنة والتنوين",
    description: "4 essential rules every reciter must know",
    icon: "ن",
    color: const Color(0xFF6A1B9A),
    duration: "20 min",
    sections: [
      LessonSection(
        title: "Rule 1 — Izhar إظهار (Clear)",
        explanation: "When noon sakinah (نْ) or tanwin is followed by a THROAT letter (ء ه ع ح غ خ):\n→ Pronounce noon CLEARLY\n→ NO nasal sound\n→ 6 throat letters only",
        arabicExample: "مِنْ عِلْمٍ — مَنْ هُوَ\nيَنْهَوْنَ — عَلِيمٌ حَكِيم",
        transliteration: "min 'ilmin, man huwa\nyanhawna, 'aleemun hakeem",
        tip: "Throat letters = clear noon. Memory: ء ه ع ح غ خ",
        exampleSurah: 96,
        exampleAyah: 5,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Rule 2 — Idgham إدغام (Merging)",
        explanation: "When noon sakinah at END of word + next word starts with يرملون:\n→ Merge noon into next letter\n→ Noon disappears!\n\nWITH Ghunnah (2 counts): ي ن م و\nWITHOUT Ghunnah: ل ر",
        arabicExample: "مِن رَّبِّكَ (no ghunnah)\nمِن نِّعْمَةٍ (with ghunnah)\nمِن وَلِيٍّ (with ghunnah)",
        transliteration: "mir-rabbika, min-ni'mah, maw-waliyy",
        tip: "Only works when noon is at END of word. Next word must start with يرملون",
        exampleSurah: 99,
        exampleAyah: 7,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Rule 3 — Iqlab إقلاب (Conversion)",
        explanation: "When noon sakinah or tanwin is before ب ONLY:\n→ Convert noon to MEEM sound\n→ Close lips slightly\n→ Hold nasal (Ghunnah) for 2 counts\n\nOnly ONE letter causes Iqlab: ب",
        arabicExample: "مِن بَعْدِ = mim-ba'di\nسَمِيعٌ بَصِيرٌ = samee'um-baseer",
        transliteration: "mim-ba'di, samee'um-baseer",
        tip: "Look for small م written above ن in Quran — that marks Iqlab!",
        exampleSurah: 2,
        exampleAyah: 181,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Rule 4 — Ikhfa إخفاء (Hiding)",
        explanation: "When noon sakinah or tanwin + any of 15 letters:\n→ HIDE the noon (between Izhar and Idgham)\n→ Hold nasal sound for 2 counts\n→ Tongue near but NOT touching\n\n15 Ikhfa letters:\nت ث ج د ذ ز س ش ص ض ط ظ ف ق ك",
        arabicExample: "مِن تَحْتِهَا\nعَن شِمَالِهِمْ\nأَنتُمْ",
        transliteration: "min-tahtiha, 'an-shimaalihim, antum",
        tip: "If letter is not ء ه ع ح غ خ (Izhar) and not يرملون (Idgham) and not ب (Iqlab) → it's Ikhfa!",
        exampleSurah: 99,
        exampleAyah: 2,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "مِنْ عِلْمٍ — noon before ع, which rule?",
        arabicText: "مِنْ عِلْمٍ",
        options: ["Ikhfa", "Iqlab", "Izhar", "Idgham"],
        correctIndex: 2,
        explanation: "ع is a throat letter → Izhar: pronounce noon clearly",
      ),
      QuizQuestion(
        question: "مِن بَعْدِ — noon before ب, which rule?",
        arabicText: "مِن بَعْدِ",
        options: ["Izhar", "Iqlab", "Idgham", "Ikhfa"],
        correctIndex: 1,
        explanation: "ب causes Iqlab → convert noon to meem sound",
      ),
      QuizQuestion(
        question: "مِن تَحْتِهَا — noon before ت, which rule?",
        arabicText: "مِن تَحْتِهَا",
        options: ["Izhar", "Idgham", "Iqlab", "Ikhfa"],
        correctIndex: 3,
        explanation: "ت is one of 15 Ikhfa letters → hide noon partially",
      ),
      QuizQuestion(
        question: "مِن رَّبِّكَ — which type of Idgham?",
        arabicText: "مِن رَّبِّكَ",
        options: ["With Ghunnah", "Without Ghunnah", "Izhar", "Iqlab"],
        correctIndex: 1,
        explanation: "ر causes Idgham WITHOUT ghunnah — noon fully merges",
      ),
      QuizQuestion(
        question: "How many Ikhfa letters are there?",
        arabicText: null,
        options: ["6", "10", "12", "15"],
        correctIndex: 3,
        explanation: "There are exactly 15 Ikhfa letters",
      ),
      QuizQuestion(
        question: "Iqlab only happens before which letter?",
        arabicText: null,
        options: ["ت", "م", "ب", "ن"],
        correctIndex: 2,
        explanation: "Only ب causes Iqlab — noon converts to meem",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_5",
    title: "Madd — Elongation",
    arabicTitle: "المدود",
    description: "When and how long to elongate vowels",
    icon: "ـا",
    color: const Color(0xFF1B5E20),
    duration: "18 min",
    sections: [
      LessonSection(
        title: "What is Madd?",
        explanation: "Madd (مد) means elongation. Three letters create long vowels:\n\n• ا after fatha (َ) → long 'aa' sound\n• و after damma (ُ) → long 'oo' sound\n• ي after kasra (ِ) → long 'ee' sound\n\nElongation is measured in COUNTS (harakaat).",
        arabicExample: "قَالَ = qaa-la (long aa)\nيَقُولُ = ya-qoo-lu (long oo)\nقِيلَ = qee-la (long ee)",
        transliteration: "qaala, yaqoolu, qeela",
        tip: "Tap your finger for each count while elongating",
        exampleSurah: 1,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Madd Tabee'i — Natural (2 counts)",
        explanation: "Basic madd with NO hamza or sukoon after madd letter.\n→ ALWAYS exactly 2 counts\n→ Most common type\n→ Cannot be more or less than 2",
        arabicExample: "قَالَ — كِتَاب — نُوح — فِي\nرَب — رَبِّ — مَالِك",
        transliteration: "qaala, kitaab, nooh, fee",
        tip: "2 counts = 2 finger taps. Quick and natural!",
        exampleSurah: 112,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Madd Muttasil — Connected (4-5 counts)",
        explanation: "Madd letter + hamza (ء) in the SAME word:\n→ 4 to 5 counts (obligatory)\n→ Cannot be reduced to 2\n→ 'Muttasil' means 'connected'",
        arabicExample: "جَاءَ — سَاءَ — جِيءَ\nسُوءَ — شَاءَ — جَاءَتْ",
        transliteration: "jaa-a, saa-a, jee-a, soo-a",
        tip: "Same word + hamza after madd letter = 4-5 counts minimum!",
        exampleSurah: 110,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Madd Lazim — Obligatory (6 counts)",
        explanation: "Madd letter followed by sukoon or shadda:\n→ ALWAYS exactly 6 counts\n→ Never less, never more\n→ Most important to get right!\n→ 'Lazim' means 'obligatory'",
        arabicExample: "الضَّالِّين — دَابَّة\nالْحَاقَّة — الصَّاخَّة",
        transliteration: "addaalleen, daabba, alhaqqa",
        tip: "6 counts = 3 pairs of taps: 1-2, 3-4, 5-6",
        exampleSurah: 1,
        exampleAyah: 7,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "How many counts for Madd Tabee'i?",
        arabicText: "قَالَ",
        options: ["1 count", "2 counts", "4 counts", "6 counts"],
        correctIndex: 1,
        explanation: "Natural madd is always exactly 2 counts — never more or less",
      ),
      QuizQuestion(
        question: "جَاءَ — what type of Madd?",
        arabicText: "جَاءَ",
        options: ["Tabee'i (2)", "Muttasil (4-5)", "Munfasil (4-5)", "Lazim (6)"],
        correctIndex: 1,
        explanation: "Hamza after madd letter in SAME word = Muttasil (4-5 counts)",
      ),
      QuizQuestion(
        question: "Madd Lazim is ALWAYS how many counts?",
        arabicText: "الضَّالِّين",
        options: ["2", "4", "5", "6"],
        correctIndex: 3,
        explanation: "Madd Lazim is always exactly 6 counts — obligatory!",
      ),
      QuizQuestion(
        question: "Which is NOT a Madd letter?",
        arabicText: null,
        options: ["ا", "و", "ب", "ي"],
        correctIndex: 2,
        explanation: "ب is not a madd letter. Only ا و ي are madd letters",
      ),
      QuizQuestion(
        question: "What triggers Madd Lazim?",
        arabicText: null,
        options: ["Hamza after madd", "Sukoon or shadda after madd", "End of verse", "Start of word"],
        correctIndex: 1,
        explanation: "Sukoon or shadda after madd letter = Madd Lazim (6 counts)",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_6",
    title: "Qalqalah — Echo Sound",
    arabicTitle: "القلقلة",
    description: "The bounce/echo of 5 special letters",
    icon: "ق",
    color: const Color(0xFFB71C1C),
    duration: "10 min",
    sections: [
      LessonSection(
        title: "What is Qalqalah?",
        explanation: "Qalqalah (قلقلة) is a slight echo or bounce added to 5 special letters when they have sukoon.\n\nThe 5 letters: ق ط ب ج د\n\nMemory trick: قُطْبُ جَدّ (qutbu jadd)\n\nWithout Qalqalah these letters sound incomplete — flat and muffled.",
        arabicExample: "ق — قُطْبُ جَدّ\nط — طَرِيق\nب — أَبُو\nج — مَجْد\nد — وَلَد",
        transliteration: "qaf, ta, ba, jeem, dal",
        tip: "Memory: قُطْبُ جَدّ contains ALL 5 Qalqalah letters!",
        exampleSurah: 112,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Minor Qalqalah — Middle of Word",
        explanation: "Qalqalah letter with sukoon in MIDDLE of word:\n→ Slight, subtle bounce\n→ Do NOT exaggerate\n→ Just enough to complete the letter sound",
        arabicExample: "يَقْطَعُونَ (ق with sukoon)\nأَبْدَعَ (ب with sukoon)\nيَجْعَلُونَ (ج with sukoon)",
        transliteration: "yaqta'oona, abda'a, yaj'aloon",
        tip: "Slight bounce — like a soft echo. Don't over-exaggerate!",
        exampleSurah: 113,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Major Qalqalah — End of Word (Waqf)",
        explanation: "When STOPPING (waqf) on a word that ends with a Qalqalah letter:\n→ STRONG, clear bounce\n→ Much more emphasis than minor\n→ The echo should be clearly heard",
        arabicExample: "الْفَلَقِ ← stop on ق\nعَلَقٍ ← stop on ق\nلَهَبٍ ← stop on ب",
        transliteration: "al-falaq, 'alaq, lahab",
        tip: "When stopping at end of verse — strong clear bounce! Let it echo.",
        exampleSurah: 113,
        exampleAyah: 1,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "What are the 5 Qalqalah letters?",
        arabicText: "قُطْبُ جَدّ",
        options: ["أبتثج", "قطبجد", "صضطظع", "ءهعحغخ"],
        correctIndex: 1,
        explanation: "Qalqalah letters: ق ط ب ج د — remembered as قُطْبُ جَدّ",
      ),
      QuizQuestion(
        question: "يَقْطَعُونَ — which letter has Qalqalah?",
        arabicText: "يَقْطَعُونَ",
        options: ["ي", "ق", "ع", "و"],
        correctIndex: 1,
        explanation: "ق has sukoon in middle of word = Minor Qalqalah",
      ),
      QuizQuestion(
        question: "الْفَلَقِ (when stopping) — type of Qalqalah?",
        arabicText: "الْفَلَقِ",
        options: ["No Qalqalah", "Minor Qalqalah", "Major Qalqalah", "Both"],
        correctIndex: 2,
        explanation: "Stopping on ق at end of word = Major Qalqalah — strong bounce",
      ),
      QuizQuestion(
        question: "Which memory phrase contains all Qalqalah letters?",
        arabicText: null,
        options: ["بسم الله", "قُطْبُ جَدّ", "الحمد لله", "لا إله إلا"],
        correctIndex: 1,
        explanation: "قُطْبُ جَدّ contains: ق ط ب ج د — all 5 Qalqalah letters",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_7",
    title: "Ghunnah & Meem Sakinah",
    arabicTitle: "الغنة وميم الساكنة",
    description: "Nasal sounds and the 3 rules of meem sakinah",
    icon: "غ",
    color: const Color(0xFF4A148C),
    duration: "15 min",
    sections: [
      LessonSection(
        title: "Ghunnah — Nasal Sound",
        explanation: "Ghunnah (غنة) is a nasal resonance produced from the nose.\n\nAlways 2 counts.\n\nApplies to:\n• Noon (ن) with shadda: إِنَّ\n• Meem (م) with shadda: ثُمَّ\n\nTest: Pinch your nose while saying إِنَّ — the sound should change!",
        arabicExample: "إِنَّ — ثُمَّ — مِنَّ\nعَنْهُمْ — لَمَّا",
        transliteration: "inna, thumma, minna, 'anhum, lamma",
        tip: "Pinch nose test: sound changes = correct ghunnah ✓",
        exampleSurah: 112,
        exampleAyah: 1,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Meem Sakinah — 3 Rules",
        explanation: "When meem has sukoon (مْ), 3 rules apply:\n\n1. IDGHAM SHAFAWI (إدغام شفوي)\n   Before م → merge with ghunnah (2 counts)\n\n2. IKHFA SHAFAWI (إخفاء شفوي)\n   Before ب → hide meem, lips almost closed, ghunnah (2 counts)\n\n3. IZHAR SHAFAWI (إظهار شفوي)\n   Before all other 26 letters → clear meem, no ghunnah",
        arabicExample: "لَهُم مَّا (Idgham)\nتَرْمِيهِم بِحِجَارَة (Ikhfa)\nلَهُمْ فِيهَا (Izhar)",
        transliteration: "lahum-maa, tarmeehim-bihijara, lahum-feeha",
        tip: "Before م = Idgham | Before ب = Ikhfa | Before everything else = Izhar",
        exampleSurah: 105,
        exampleAyah: 4,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "Ghunnah lasts how many counts?",
        arabicText: "إِنَّ",
        options: ["1 count", "2 counts", "4 counts", "6 counts"],
        correctIndex: 1,
        explanation: "Ghunnah is always 2 counts — no more, no less",
      ),
      QuizQuestion(
        question: "لَهُم مَّا — which meem rule?",
        arabicText: "لَهُم مَّا",
        options: ["Izhar Shafawi", "Ikhfa Shafawi", "Idgham Shafawi", "No rule"],
        correctIndex: 2,
        explanation: "Meem sakinah before meem = Idgham Shafawi — merge with ghunnah",
      ),
      QuizQuestion(
        question: "تَرْمِيهِم بِحِجَارَة — which rule?",
        arabicText: "تَرْمِيهِم بِحِجَارَة",
        options: ["Idgham", "Izhar Shafawi", "Ikhfa Shafawi", "Iqlab"],
        correctIndex: 2,
        explanation: "Meem sakinah before ب = Ikhfa Shafawi — hide meem with ghunnah",
      ),
      QuizQuestion(
        question: "لَهُمْ فِيهَا — which rule?",
        arabicText: "لَهُمْ فِيهَا",
        options: ["Idgham Shafawi", "Ikhfa Shafawi", "Izhar Shafawi", "Ghunnah"],
        correctIndex: 2,
        explanation: "Meem sakinah before ف = Izhar Shafawi — clear meem, no ghunnah",
      ),
      QuizQuestion(
        question: "How to test if Ghunnah is correct?",
        arabicText: null,
        options: ["Open mouth wide", "Pinch your nose", "Touch teeth", "Close eyes"],
        correctIndex: 1,
        explanation: "Pinch nose while reciting — if sound changes, ghunnah is correct!",
      ),
    ],
  ),
  TajweedLesson(
    id: "lesson_8",
    title: "Waqf & Ibtida — Stopping Rules",
    arabicTitle: "الوقف والابتداء",
    description: "When and where to stop and start in Quran recitation",
    icon: "وق",
    color: const Color(0xFF004D40),
    duration: "12 min",
    sections: [
      LessonSection(
        title: "What is Waqf?",
        explanation: "Waqf (وقف) means stopping during recitation. Ibtida (ابتداء) means starting again.\n\nStopping in wrong place can completely change meaning!\n\nExample: Wrong stop in Surah Al-Fatiha changes the meaning of the verse.",
        arabicExample: "Wrong: إِيَّاكَ نَعْبُدُ (stop) وَإِيَّاكَ\nCorrect: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
        transliteration: "iyyaka na'budu wa iyyaka nasta'een",
        tip: "Always complete the meaning before stopping!",
        exampleSurah: 1,
        exampleAyah: 5,
        showWordByWord: true,
      ),
      LessonSection(
        title: "Waqf Signs in the Quran",
        explanation: "The Quran has special symbols showing where to stop:\n\n• م (Waqf Lazim) — MUST stop here\n• لا (La waqf) — Do NOT stop here\n• ج (Waqf Jaiz) — May stop here\n• ط (Waqf Mutlaq) — Better to stop\n• ص (Waqf Murakhkhas) — Can stop if short of breath\n• ∴ (Mu'anaqah) — Stop on ONE of two marks, not both",
        arabicExample: "مـ = must stop\nلا = do not stop\nج = may stop",
        transliteration: "meem = stop | laa = continue | jeem = optional",
        tip: "Look for these symbols in your Quran above/below words",
        exampleSurah: 1,
        exampleAyah: 7,
        showWordByWord: false,
      ),
      LessonSection(
        title: "Rules When Stopping (Waqf)",
        explanation: "When you stop on a word:\n\n1. Last letter loses its vowel (becomes saakin)\n2. Tanwin becomes just the vowel (ً→ا, ٌ→, ٍ→)\n3. Teh marbuta (ة) becomes haa (ه) or silent\n4. Qalqalah letters get strong bounce\n5. You can stretch madd letters at end",
        arabicExample: "رَحِيمٌ (in middle) → رَحِيمْ (when stopping)\nرَحْمَة (in middle) → رَحْمَهْ (when stopping)",
        transliteration: "raheemun → raheem | rahmatun → rahmah",
        tip: "Stopping changes how last letter sounds — practice this!",
        exampleSurah: 1,
        exampleAyah: 3,
        showWordByWord: true,
      ),
    ],
    questions: [
      QuizQuestion(
        question: "What does Waqf mean?",
        arabicText: "وقف",
        options: ["Starting recitation", "Stopping recitation", "Speed of recitation", "Tone of recitation"],
        correctIndex: 1,
        explanation: "Waqf means stopping — knowing when to stop is essential",
      ),
      QuizQuestion(
        question: "What does مـ sign mean in Quran?",
        arabicText: "مـ",
        options: ["May stop", "Do not stop", "Must stop", "Stop if tired"],
        correctIndex: 2,
        explanation: "م (Waqf Lazim) means you MUST stop here",
      ),
      QuizQuestion(
        question: "What does لا sign mean?",
        arabicText: "لا",
        options: ["Must stop", "Do not stop", "May stop", "Rest here"],
        correctIndex: 1,
        explanation: "لا means do NOT stop here — stopping changes meaning",
      ),
      QuizQuestion(
        question: "When stopping, tanwin (ً) becomes?",
        arabicText: "رَحِيمٌ",
        options: ["Silent", "Long alef", "Short vowel only", "Double noon"],
        correctIndex: 0,
        explanation: "When stopping, tanwin loses its 'n' sound — becomes silent",
      ),
      QuizQuestion(
        question: "What happens to Qalqalah letters at Waqf?",
        arabicText: "الْفَلَقِ",
        options: ["They disappear", "They get stronger bounce", "They become silent", "They lengthen"],
        correctIndex: 1,
        explanation: "Qalqalah at waqf = Major Qalqalah — strong bounce!",
      ),
    ],
  ),
];

